<script>
import SlidingMenu from "$lib/settings/templates/SlidingMenu.svelte";
import Option from "$lib/settings/templates/Option.svelte";
import DevicesMenu from "$lib/devices/DevicesMenu.svelte";
import { twoFACheckStore } from "$lib/stores/twofa-check.js";
import { invalidate } from "$app/navigation";
import { globalUser } from "$lib/stores/user";

export let socket;
export let displaySettings;
export let toggleSettings;

let displayGeneral = false;
let displaySecurity = false;
let displayEncryption = false;
let displayEncryptionConfirm = false;
let encryptionButtonDisabled = false;
let displaySusFiles = false;  // Scan suspicious files menu 
let displayMagic = false;     // Disappearing messages menu, *MAGIC! POOF!* (๑°༥°๑)
let displayData = false;
let displayDevices = false;
let displayTwoFactor = false;
let displayTwoFactorEnabling = false;
let displayBackupCode = false;
let displayFilesRequested = true;

const toggleGeneral = async () => displayGeneral = !displayGeneral;
const toggleSecurity = async () => displaySecurity = !displaySecurity;
const toggleEncryption = async () => displayEncryption = !displayEncryption;
const toggleSusFiles = async () => displaySusFiles = !displaySusFiles;
const toggleMagic = async () => displayMagic = !displayMagic;
const toggleData = async () => displayData = !displayData;
const toggleTwoFactor = async () => displayTwoFactor = !displayTwoFactor;
const toggleTwoFactorEnabling = async () => displayTwoFactorEnabling = !displayTwoFactorEnabling;
const toggleBackupCode = async () => displayBackupCode = !displayBackupCode;
const toggleFilesRequested = async () => displayFilesRequested = !displayFilesRequested;
const currentUser = $globalUser;
let twoFaSecretToken;
let twoFAInput = "";
let backupCodes = "";

async function toggleDevices () {
  displayDevices = !displayDevices;
  invalidate("app:devices");
}

async function sendDataRequest () {
  const response = await fetch("https://localhost:8443/api/settings/account-information", {
    headers: {
      "Content-Type": "application/json"
    },
    credentials: "include",
    method: "GET"
  });
  if (response.ok) {
    toggleFilesRequested();
  }
}

async function enableTwoFA () {
  const response = await fetch("https://localhost:8443/api/settings/twofa_secretgenerate", {
    headers: {
      "Content-Type": "application/json"
    },
    credentials: "include",
  });
  
  const data = await response.json();
  if (response.ok) {
    twoFaSecretToken = data.secret;
    toggleTwoFactorEnabling();
  }
}

async function disableTwoFA () {
  const response = await fetch("https://localhost:8443/api/settings/twofa-delete", {
    headers: {
      "Content-Type": "application/json"
    },
    credentials: "include",
    method: "DELETE"
  });
  if (response.ok) {
    toggleTwoFactor();
  }
}

async function submitTwoFA () {
  const response = await fetch ("https://localhost:8443/api/settings/twofa", {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    credentials: "include",
    body: JSON.stringify({
      twofacode: twoFAInput
    })
  });
  const data = await response.json();
  if (response.ok) {
    toggleTwoFactor();
    toggleTwoFactorEnabling();
    backupCodes = data.backup_codes.join(", ");
    toggleBackupCode();
    invalidate("app:twofa-check");
  }
}

async function enableEncryption() {
  socket.emit("enable_e2ee");
}
</script>

<SlidingMenu title="Settings" display={displaySettings} on:click={toggleSettings}>
  <div class="profile-section d-flex flex-row align-items-center p-1">
    <div class="profile p-1">
      <div class="img-wrapper img-1-1">
        <img class="rounded-circle p-2" src={currentUser.avatar} alt="">
      </div>
    </div>
    <div class="ms-2 fs-4 user-select-none">{currentUser.username}</div>
  </div>
  <div class="d-flex flex-column">
    <Option name="General Settings" icon="gear" on:click={toggleGeneral}/>
    <Option name="Privacy and Security" icon="lock" on:click={toggleSecurity}/>
    <Option name="Devices" icon="desktop" on:click={toggleDevices}/>
  </div>
</SlidingMenu>


<SlidingMenu title="General Settings" display={displayGeneral} on:click={toggleGeneral}>
  <Option name="Two Factor Authentication" icon="shield" on:click={toggleTwoFactor}/>
</SlidingMenu>
<SlidingMenu title="Two Factor Authentication" display={displayTwoFactor} on:click={toggleTwoFactor}>
  <div class="info-box">
    <p>Two Factor Authentication is a method of confirming your identity by using two different methods. The first method is your password, and the second method is a code generated by an app on your phone. This code changes every 30 seconds, and is only valid for 30 seconds. This means that even if someone gets your password, they still can't log in without your phone.</p>
    <p>Two Factor Authentication is highly recommended, and is required for some accounts.</p>
    <p>Two Factor Authentication is currently <b>{ $twoFACheckStore ? "enabled" : "disabled" }</b>.</p>
    {#if $twoFACheckStore}
    <button class="btn btn-primary" on:click={disableTwoFA}>Disable Two Factor Authentication</button>
    {:else}
    <button class="btn btn-primary" on:click={enableTwoFA}>Enable Two Factor Authentication</button>
    {/if}
  </div>
</SlidingMenu>
<SlidingMenu title="Two Factor Authentication" display={displayTwoFactorEnabling} on:click={toggleTwoFactorEnabling}>
  <div>
    <p>Follow these steps to enable Two Factor Authentication:</p>
    <ol>
      <li>Download the <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en_US&gl=US">Authenticator App</a> on your phone.</li>
      <li>Open the app and scan the QR code below.</li>
      <li>If the QR code fails to load, enter the setup key shown.</li>
      <li>Enter the code generated by the app.</li>
    </ol>
    <img class="QR2fa" src="https://localhost:8443/api/settings/2fa/qr-code/{ twoFaSecretToken }" alt="{ twoFaSecretToken }" />
    <form class="form2fa" on:submit={submitTwoFA}>
      <input type="text" name="2faCode" id="2faCode" bind:value={twoFAInput} placeholder="Enter the code generated by the app" />
      <button class="btn btn-primary">Submit</button>
    </form>
  </div>
</SlidingMenu>
<SlidingMenu title="Backup Code" display={displayBackupCode} on:click={toggleBackupCode}>
  <div>
    <p>Here is your backup code. Write it down and keep it somewhere safe. If you lose your phone, you can use this code to log in. Do note that when one of the code is used, that said code will no longer be usable.</p>
    <p>Backup codes: <b>{ backupCodes}</b></p>
  </div>
</SlidingMenu>

<SlidingMenu title="Privacy and Security" display={displaySecurity} on:click={toggleSecurity}>
  <Option name="End-to-end encryption" icon="lock" on:click={toggleEncryption}/>
  <Option name="Scan incoming files" icon="file-shield" on:click={toggleSusFiles}/>
  <Option name="Disappearing messages" icon="stopwatch" on:click={toggleMagic}/>
  <Option name="Request personal data" icon="file-zipper" on:click={toggleData}/>
</SlidingMenu>
<SlidingMenu title="End-to-end encryption" display={displayEncryption} on:click={() => {displayEncryptionConfirm = false; toggleEncryption()}}>
  <div class="info-box e2ee-section">
    <p>
      End-to-end encryption keeps your messages from being accessed by outsiders. Not even Bubbles can know what your messages are. <span class="green">To turn on this feature, you have to bind this account to your Google account.</span>
    </p>
    <p>
      Currently only direct chats supports end-to-end encryption. End-to-end encryption will only be active if both users in the direct chat has end-to-end encryption enabled. Chats that are end-to-end encrypted will be labelled with a green lock <i class="fa-solid fa-lock green"></i>.
    </p>
    <p>
      The secret keys for encrypting your messages will be stored in your Google Drive, where only you can access it.
      <span class="red">
        You must <strong>NOT</strong> clear the Bubbles app data stored in your Google Drive. Doing so will result in the loss of your keys and consequently your messages as well.
      </span>
    </p>
    {#if $globalUser.e2ee}
      <strong class="green">End-to-end encryption is already enabled :)</strong>
    {:else if displayEncryptionConfirm}
      <strong>Note: this action is irreversible!</strong>
      <button class="btn w-100 mb-1" on:click={() => {
        enableEncryption();
        encryptionButtonDisabled = true;
        displayEncryptionConfirm = false;
      }}>
        Enable
      </button>
      <button class="btn red w-100" on:click={() => displayEncryptionConfirm = false}>
        Cancel
      </button>
    {:else}
      <button class="btn w-100" on:click={() => displayEncryptionConfirm = true} disabled={encryptionButtonDisabled}>
        Enable end-to-end encryption.
      </button>
    {/if}
  </div>
</SlidingMenu>
<SlidingMenu title="Scan incoming files" display={displaySusFiles} on:click={toggleSusFiles}>
  <div class="info-box">
    <p>
      Bubbles can scan incoming files for viruses and malware. This is highly recommended for all accounts and on by default.
    </p>
  </div>
</SlidingMenu>
<SlidingMenu title="Disappearing messages" display={displayMagic} on:click={toggleMagic}>
  <div class="info-box">
    <p>
      Messages sent will automatically delete themselves after a certain amount of time. This is to prevent messages from potentially being leaked and read by others. This feature can be enabled in direct chats by either user, and in group chats by administrators.
    </p>
  </div>
</SlidingMenu>
<SlidingMenu title="Request personal data" display={displayData} on:click={toggleData}>
  <div class="file-icon">
    <i class="fa-solid fa-print"></i>
  </div>
  <div class="p-data">
    <span class="p-data-disclaimer">
      Bubbles can export all of your data, including account information and friends.
    </span>
  </div>
  <hr>
  {#if (displayFilesRequested)}
    <form action="" on:submit={sendDataRequest}>
      <div class="d-grid mx-3">
        <button class="d-flex justify-content-center align-items-center req-data py-2">
          <i class="fa-solid fa-file"></i>
          <span>
            Request personal data
          </span>
        </button>
      </div>
    </form>
  {:else}
    <div><p class="requested-data">Report sent. It will be sent to your email shortly.</p></div>
  {/if}
  <hr>
  <div class="p-data">
    <span class="p-data-disclaimer">
      <b>A download link</b> will be sent to you when the report is available for download. Because this report contains your information, you should be careful about storing, sending, or uploading it to any other services.
    </span>
  </div>
</SlidingMenu>


<SlidingMenu title="Devices" display={displayDevices} on:click={toggleDevices}>
  <DevicesMenu />
</SlidingMenu>

<style>
.info-box{
  padding: 1rem;
  margin: 1rem;
  border: 1px solid var(--grey);
  border-radius: 3px;
}
.profile-section:hover {
  background-color: var(--grey-light);
}
.profile {
  width: 5rem;
}

.p-data {
  display: flex;
  flex-direction: column;
  font-size: 1rem; 
  padding-top: 1rem;
  padding-bottom: 1rem;
  padding-left: 2rem;
  padding-right: 2rem;
}

.req-data {
  border: 1 solid black;
  border-radius: 0.5rem;
  background-color: inherit;
}

.fa-solid {
  font-size: 2.5rem;
  margin-right: 10px;
  padding-left:1rem;
} 

.file-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  padding-top: 1rem;
  padding-bottom: 1rem;
  padding-left: 2rem;
  padding-right: 2rem;
}

.requested-data{
  opacity: 0.7;
  font-size: 1rem;
  text-align: center;
}

.QR2fa {
  width: 150px;
  height: 150px;
  margin: 0 auto;

}

.form2fa {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 10px;
  margin-bottom: 10px;
}

.e2ee-section p {
  text-align: justify;
}

.e2ee-section .btn {
  background-color: var(--primary);
  color: var(--white);
}

.e2ee-section .btn:hover {
  background-color: var(--primary-highlight);
}

.e2ee-section .btn:active {
  background-color: var(--highlight-primary);
  color: var(--primary);
}

.e2ee-section .btn.red {
  background-color: var(--red);
}

.e2ee-section .btn.red:hover {
  background-color: var(--red-highlight);
}

.e2ee-section .btn.red:active{
  background-color: var(--red-light-background);
  color: var(--red);
}

.e2ee-section i {
  font-size: inherit;
  padding: 0;
  margin: 0;
}

.green {
  color: var(--primary);
}

.red {
  color: var(--red);
}
</style>