<script>
import SlidingMenu from "$lib/settings/templates/SlidingMenu.svelte";
import Option from "$lib/settings/templates/Option.svelte";
import DevicesMenu from "$lib/devices/DevicesMenu.svelte";
import { invalidate } from "$app/navigation";
import { page } from "$app/stores";

export let displaySettings;
export let toggleSettings;

let displayGeneral = false;
let displaySecurity = false;
let displaySusFiles = false;  // Scan suspicious files menu 
let displayMagic = false;     // Disappearing messages menu, *MAGIC! POOF!* (๑°༥°๑)
let displayData = false;
let displayDevices = false;
let displayTwoFactor = false;
let displayTwoFactorEnabling = false;
let displayBackupCode = false;

const toggleGeneral = async () => displayGeneral = !displayGeneral;
const toggleSecurity = async () => displaySecurity = !displaySecurity;
const toggleSusFiles = async () => displaySusFiles = !displaySusFiles;
const toggleMagic = async () => displayMagic = !displayMagic;
const toggleData = async () => displayData = !displayData;
const toggleTwoFactor = async () => displayTwoFactor = !displayTwoFactor;
const toggleTwoFactorEnabling = async () => displayTwoFactorEnabling = !displayTwoFactorEnabling;
const toggleBackupCode = async () => displayBackupCode = !displayBackupCode;
const currentUser = $page.data.user;
let twoFaSecretToken;
let twoFAInput = "";
let backupCode = "";

async function toggleDevices () {
  displayDevices = !displayDevices;
  invalidate("app:devices");
}

async function enableTwoFA () {
  const response = await fetch("https://localhost:8443/api/settings/twofa_secretgenerate", {
    headers: {
      "Content-Type": "application/json"
    },
    credentials: "include",
  });
  
  const data = await response.json();
  if (response.ok) {
    twoFaSecretToken = data.secret;
    toggleTwoFactorEnabling();
  }
}

async function disableTwoFa () {
  await fetch("https://localhost:8443/api/settings/twofa-delete", {
    headers: {
      "Content-Type": "application/json"
    },
    credentials: "include",
  });
}

async function submitTwoFA () {
  await fetch ("https://localhost:8443/api/settings/twofa", {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    credentials: "include",
    body: JSON.stringify({
      twofacode: twoFAInput
    })
  });
}

</script>

<SlidingMenu title="Settings" display={displaySettings} on:click={toggleSettings} right={false}>
  <div class="">
    Profile things here...
  </div>
  <div class="d-flex flex-column">
    <Option name="General Settings" icon="gear" on:click={toggleGeneral}/>
    <Option name="Privacy and Security" icon="lock" on:click={toggleSecurity}/>
    <Option name="Devices" icon="desktop" on:click={toggleDevices}/>
  </div>
</SlidingMenu>


<SlidingMenu title="General Settings" display={displayGeneral} on:click={toggleGeneral} right={true}>
  <Option name="Two Factor Authentication" icon="shield" on:click={toggleTwoFactor}/>
</SlidingMenu>
<SlidingMenu title="Two Factor Authentication" display={displayTwoFactor} on:click={toggleTwoFactor} right={true}>
  <div>
    <p>Two Factor Authentication is a method of confirming your identity by using two different methods. The first method is your password, and the second method is a code generated by an app on your phone. This code changes every 30 seconds, and is only valid for 30 seconds. This means that even if someone gets your password, they still can't log in without your phone.</p>
    <p>Two Factor Authentication is highly recommended, and is required for some accounts.</p>
    <p>Two Factor Authentication is currently <b>{ currentUser.twofa_status ? "enabled" : "disabled" }</b>.</p>
    {#if currentUser.twofa_status}
    <button class="btn btn-primary" on:click={disableTwoFa}>Disable Two Factor Authentication</button>
    {:else}
    <button class="btn btn-primary" on:click={enableTwoFA}>Enable Two Factor Authentication</button>
    {/if}
  </div>
</SlidingMenu>
<SlidingMenu title="Two Factor Authentication" display={displayTwoFactorEnabling} on:click={toggleTwoFactorEnabling} right={true}>
  <div>
    <p>Follow these steps to enable Two Factor Authentication:</p>
    <ol>
      <li>Download the <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en_US&gl=US">Authenticator App</a> on your phone.</li>
      <li>Open the app and scan the QR code below.</li>
      <li>If the QR code fails to load, enter the setup key shown.</li>
      <li>Enter the code generated by the app.</li>
    </ol>
    <img class="QR2fa" src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=otpauth://totp/Bubbles Authenticator ({ currentUser.username })?secret={ twoFaSecretToken }&issuer=Bubbles" alt="{ twoFaSecretToken }" />
    <form class="form2fa" on:submit={submitTwoFA}>
      <input type="text" name="2faCode" id="2faCode" bind:value={twoFAInput} placeholder="Enter the code generated by the app" />
      <button class="btn btn-primary">Submit</button>
    </form>
  </div>
</SlidingMenu>
<SlidingMenu title="Backup Code" display={displayBackupCode} on:click={toggleBackupCode} right={true}>
  <div>
    <p>Here is your backup code. Write it down and keep it somewhere safe. If you lose your phone, you can use this code to log in.</p>
    <p>Backup codes: <b>{ backupCode[1] }, { backupCode[2] }, { backupCode[3] }, { backupCode[4] }, { backupCode[5] }, { backupCode[6] }</b></p>
  </div>
</SlidingMenu>

<SlidingMenu title="Privacy and Security" display={displaySecurity} on:click={toggleSecurity} right={true}>
  <Option name="Scan incoming files" icon="file-shield" on:click={toggleSusFiles}/>
  <Option name="Disappearing messages" icon="stopwatch" on:click={toggleMagic}/>
  <Option name="Request personal data" icon="file-zipper" on:click={toggleData}/>
</SlidingMenu>
<SlidingMenu title="Scan incoming files" display={displaySusFiles} on:click={toggleSusFiles} right={true}>
</SlidingMenu>
<SlidingMenu title="Disappearing messages" display={displayMagic} on:click={toggleMagic} right={true}>
</SlidingMenu>
<SlidingMenu title="Request personal data" display={displayData} on:click={toggleData} right={true}>
</SlidingMenu>


<SlidingMenu title="Devices" display={displayDevices} on:click={toggleDevices} right={true}>
  <DevicesMenu />
</SlidingMenu>

<style>
.QR2fa {
  width: 150px;
  height: 150px;
  margin: 0 auto;

}

.form2fa {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 10px;
  margin-bottom: 10px;
}
</style>